global:
  scrape_interval: 30s
  external_labels:
    scraped_by: prometheus-cortex-1

scrape_configs:
  - job_name: avalanche
    static_configs:
      - targets: ['xx:9001', 'xx:9002', 'xx:9003', 'xx:9004', 'xx:9005', 'xx:9006']
      - targets: ['xx:9007', 'xx:9008', 'xx:9009', 'xx:9010', 'xx:9011', 'xx:9012']
      - targets: ['xx:9013', 'xx:9014', ’xx:9015', 'xx:9016']
remote_write:
  - url: http://nginx:8004/api/v1/push
    headers:
      X-Scope-OrgID: avalanche
    queue_config:
    # some tweaks to reduce load on /push?:
      max_samples_per_send: 500 
      # default 500
      min_backoff: 100ms 
      # default 30ms
      max_backoff: 1000ms 
      # default 100ms

